---
abstract: 'Perl class for Czech RC identification generation.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Person-ID-CZ-RC-Generator
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  DateTime: 0
  English: 0
  Error::Pure: 0.11
  List::Util: 1.33
  Random::Day: 0.01
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Person-ID-CZ-RC-Generator/issues
  homepage: https://github.com/michal-josef-spacek/Person-ID-CZ-RC-Generator
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Person-ID-CZ-RC-Generator
version: '0.06'
